{
    "workbench.colorCustomizations": {
        "tab.activeBorder": "#ffb81e",
        "terminal.ansiBlack": "#000000",
        "terminal.ansiRed": "#c23621",
        "terminal.ansiGreen": "#25bc24",
        "terminal.ansiYellow": "#adad27",
        "terminal.ansiBlue": "#492ee1",
        "terminal.ansiMagenta": "#d338d3",
        "terminal.ansiCyan": "#33bbc8",
        "terminal.ansiWhite": "#cbcccd",
        "terminal.ansiBrightBlack": "#818383",
        "terminal.ansiBrightRed": "#fc391f",
        "terminal.ansiBrightGreen": "#31e722",
        "terminal.ansiBrightYellow": "#eaec23",
        "terminal.ansiBrightBlue": "#5833ff",
        "terminal.ansiBrightMagenta": "#f935f8",
        "terminal.ansiBrightCyan": "#14f0f0",
        "terminal.ansiBrightWhite": "#e9ebeb",
        "terminal.foreground": "#ffb0a2",
        "terminal.background": "#15303b",
    },
    "workbench.sideBar.location": "left",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Nord",
    "workbench.editor.tabSizing": "shrink",
    "terminal.integrated.fontFamily": "Consolas",
    "terminal.integrated.fontSize": 12,
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.cursorStyle": "underline",
    "terminal.integrated.copyOnSelection": true,
    // ///////////////////////////////////////////////////////
    "editor.fontFamily": "Fira Code,Consolas,Ubuntu Mono,Inconsolata, Monaco, DeJavu Sans Mono, Courier New, monospace",
    "editor.fontSize": 14,
    "editor.mouseWheelZoom": true,
    "editor.rulers": [80,
    100,
    120],
    "editor.renderIndentGuides": true,
    "editor.renderWhitespace": "none",
    "editor.lineNumbers": "on",
    "editor.wordWrap": "off",
    "editor.fontLigatures": true,
    "editor.renderLineHighlight": "all",
    "editor.cursorBlinking": "smooth",
    "editor.cursorStyle": "underline-thin",
    "editor.lineHeight": 22,
    "editor.formatOnType": true,
    "editor.letterSpacing": 0.5,
    "editor.tabSize": 2,
    "editor.minimap.enabled": true,
    "editor.minimap.showSlider": "always",
    "editor.fontWeight": "400",
    "editor.formatOnPaste": false,
    // /////////////////////////////////////////
    "files.autoSave": "afterDelay",
    "vsicons.dontShowNewVersionMessage": true,
    "window.zoomLevel": 0,
    "git.confirmSync": false,
    "material-icon-theme.showUpdateMessage": false,
    "extensions.ignoreRecommendations": false,
    "[javascript]": {},
    "javascript.format.insertSpaceBeforeFunctionParenthesis": false,
    "material-icon-theme.folders.theme": "specific",
    "files.trimTrailingWhitespace": true,
    "window.menuBarVisibility": "toggle",
    "prettier.printWidth": 100,
    "prettier.singleQuote": true,
    "prettier.tabWidth": 2,
    "prettier.eslintIntegration": true,
    "eslint.alwaysShowStatus": true,
    "vscode_custom_css.imports": [
        "file:///E:/GitHub/dotfiles/.vscodestyles.css"
    ],
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
}